<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Laporan SPP {{ $tahun }}</title>
    <style>
        body { font-family: Arial, sans-serif; font-size: 12px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        .table th, .table td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        .table th { background-color: #f8f9fa; font-weight: bold; }
        .badge { padding: 2px 6px; border-radius: 3px; font-size: 10px; display: inline-block; margin: 1px; }
        .success { background-color: #d4edda; color: #155724; }
        .warning { background-color: #fff3cd; color: #856404; }
        .info { background-color: #d1ecf1; color: #0c5460; }
        .footer { margin-top: 20px; text-align: right; font-size: 10px; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h2>LAPORAN SPP TAHUN {{ $tahun }}</h2>
        <p>Sekolah Example - Dicetak pada: {{ now()->format('d/m/Y H:i') }}</p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>No</th>
                <th>Nama Murid</th>
                <th>Email</th>
                <th>Bulan Sudah Bayar</th>
                <th>Bulan Belum Bayar</th>
                <th>Total Bayar</th>
                <th>Total Belum</th>
            </tr>
        </thead>
        <tbody>
            @foreach($dataMurid as $index => $data)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td>{{ $data['murid']->nama }}</td>
                <td>{{ $data['murid']->email }}</td>
                <td>
                    @if(count($data['sudah_bayar']) > 0)
                        @foreach($data['sudah_bayar'] as $bulan)
                            <span class="badge success">{{ $bulan['nama_bulan'] }}</span>
                        @endforeach
                    @else
                        <span>-</span>
                    @endif
                </td>
                <td>
                    @if(count($data['belum_bayar']) > 0)
                        @foreach($data['belum_bayar'] as $bulan)
                            <span class="badge warning">{{ $bulan['nama_bulan'] }}</span>
                        @endforeach
                    @else
                        <span class="badge success">Semua Lunas</span>
                    @endif
                </td>
                <td>{{ count($data['sudah_bayar']) }} Bulan</td>
                <td>{{ count($data['belum_bayar']) }} Bulan</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by SPP App - {{ now()->format('d/m/Y H:i') }}</p>
    </div>
</body>
</html>